Algoritmo final
	Definir muestra Como Caracter
	definir long, f, c  como entero
	
	muestra = "ACCDBBADDDCCBACABDCBDCBADBDACBBBBDAABBCCBAACCABDBDCDDABDBDADAAACBBBBCDDDCBBBDDCDABBDDABDBDBBACADCDAAADACDDDACCDCACDDABACDCCCAABDDCCACDADDBCBAACCDBCBCDDDCAACCBAADCBBBCDCBBACBDCCDDADBABCAABBACABDCAACCBDADDCAAACCDBDBBCDDDDDACBCDDADDDDCBADADBDCADDABBCDAACBCCDDDADDADADAACCACDCDDABCCCADABBACDACCAADDBCBCCDADBCCADAAABDDDAABBABCADDCCAADDCDDCDCACBADADACADDAADCBDBCDBDDACDCBCDCCABBDCBACDDACCCDADBCADCACAAABBBCADDDDBCBACDBDAAADDDACCDACBBBADACCCDCACCBACDADBCBBDADACABAACBCCADDCCCCACCCCADBCCDAADCAABBABAADDBDADDABABCCABBCDDACCADAAADBBCCDBADCADCBBDADACCDDBCAAABBBDCAAAACBAADBABBABACDDBBCBDCDCADABABBDADCBADAACDBCBDABADBCBADCACADAABCDDCABACDDBDCBCBDCAAACBDABBCACBACCCBACACDCADBDCDCDDCAACDBDCBACDBBDAABDBBCBAAADBABDBAACAAACDCDAAABABDDDBCACADCBBAADCCDABCCCBBCACCBAABDAADDDCDACDDDBCDCCBABDABACCDCDCDABAABCABBADADCBDDACDDCDDCDACDADADCACBCDABABDDCCDBCCDABACDBDAABDBDDDBADDBACABDCDDBACDDBBDDBBACBCCAACABBDADDBCAACCBCCDADDBCAADDADCCCBAAABABBBBBCABAACADBCBBABACCABCDAABADCCCCDCCADDDCCABBDDDAAADDADACBBBCBDAADACABABBAACCCADADDABDBCADDDCCDBBCCBCDCDBDDDDCACDACDBBBDDBADDACADDADDABCACDCBBADDABBBDCBBDCDAABADDDDDBCACCCCAAACBCBCDBACCCDACCCDBCBDCBADBCDDACCDBDBDBCAAACDDCBAABDBCAADCADDBABABDCBCBCBBBCACBCADDCAAAAAACBBACBBCCACBDCDDDDADCAAACBABDDBDADBAADCBABDDBCDBABDBAADDDBACBBBCCCDBDDBDDAADBBADADDDCBCACBABCDBBABAADABCABCDBACBBBCDBADADDBDCBDABBDDDCDDCCACDCBDCADABAABCDCAACCDDBADBDBCDACAAACBCADCCCBAC"
	long = longitud(muestra)
	
	si long / 3 == 3 Entonces
		f = 3
		c = 3
		crearmatriz(f, c, muestra, long)
	sino 
		si long / 4 == 4 Entonces
			f = 4
			c = 4
			crearmatriz(f, c, muestra, long)
		sino 
			si long / 37 == 37 Entonces
				f = 37
				c = 37
				crearmatriz(f, c, muestra, long)	
			sino
				ESCRIBIR"la frase es no permite hacer una matriz de 3X3 O 4X4 O 37X37"
			finsi 
		
		FinSi
		
	finsi 
	
	
FinAlgoritmo

Subproceso crearmatriz(f Por Referencia,c Por referencia,muestra por valor, long por referencia )
	definir i,j,a,b Como Entero
	definir matriz Como Caracter
	a = 0
	b = 0
	dimension matriz(f,c)
	para i = 0 Hasta f - 1 Hacer
		para j = 0 Hasta c -1  Hacer
			matriz(i,j) = subcadena(muestra,a,b)
			a = a + 1
			b = b + 1
			escribir matriz(i,j) , " " sin saltar
		FinPara
		escribir" "
	FinPara
	genZ(matriz, long,c)
FinSubProceso

Subproceso genZ(matriz,long,c)
	Definir i, j Como Entero
	Definir gen1, gen2 Como Caracter
	Definir existeGen Como Logico
	
	existeGen = Verdadero
	
	gen1 = matriz[0,0]
	gen2 = matriz[0,c-1]
	
	Para i = 0 Hasta c - 1
		Si gen1 <> matriz[i,i] Entonces
			existeGen = Falso
		FinSi
		
		Si gen2 <> matriz[i,c-1-i] Entonces
			existeGen = Falso
		FinSi
		
	FinPara
	
	Si existeGen == Verdadero Entonces
		Escribir "El gen Z ha sido detectado en la muestra!"
	SiNo
		Escribir "El gen Z no está presente en la muestra analizada."
	FinSi
FinSubProceso
